purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.279628791147843
  brandStrength: 0
  lightness: 0.3087181067094207
  brandColors:
    - '#000000'
    - '#f1f0f6'
    - '#3a4653'
    - '#cdb9a9'
    - '#7e7d83'
  rhythmicContrast: 0.25
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: Oxygen
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.25057
layout_spectrum: 0.906015
