name: Oxygen
favicon: null
layout_spectrum: 0.6478732605464756
typography_spectrum: 0.25057
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f1f0f6'
    - '#3a4653'
    - '#cdb9a9'
    - '#7e7d83'
  brandStrength: 0.25
  lightness: 0.3087181067094207
  saturation: 0.279628791147843
  rhythmicContrast: 0.5850319666787982
purpose: []
